//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emp_Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employee
    {
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string ContactNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Password1 { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string DeleteFlag { get; set; }
    
        public virtual Tbl_Role Tbl_Role { get; set; }
    }
}
